(() => {
"use strict";
const C=window.NUR_CONFIG;
const PRAYERS=[["Fajr","Subuh"],["Dhuhr","Zohor"],["Asr","Asar"],["Maghrib","Maghrib"],["Isha","Isyak"]];
const DHIKR=[{id:"subhanallah",name:"Subhanallah",target:33},{id:"alhamdulillah",name:"Alhamdulillah",target:33},{id:"allahuakbar",name:"Allahu Akbar",target:33},{id:"astaghfirullah",name:"Astaghfirullah",target:100}];
const LESSONS=[
{id:"islam",title:"Rukun Islam",intro:"Lima asas utama dalam amalan Islam.",body:`<p>Rukun Islam ialah lima perkara asas yang menjadi amalan utama seorang Muslim:</p><ol><li>Syahadah</li><li>Solat</li><li>Zakat</li><li>Puasa Ramadan</li><li>Haji bagi yang mampu</li></ol><p>Kelima-limanya mempunyai perincian hukum dan pelaksanaan yang boleh dipelajari dengan bimbingan guru.</p>`},
{id:"iman",title:"Rukun Iman",intro:"Enam perkara asas yang menjadi pegangan iman.",body:`<p>Rukun Iman ialah beriman kepada:</p><ol><li>Allah</li><li>Malaikat</li><li>Kitab-kitab Allah</li><li>Rasul-rasul Allah</li><li>Hari Akhirat</li><li>Qada dan Qadar</li></ol>`},
{id:"wuduk",title:"Wuduk",intro:"Pengenalan ringkas kepada bersuci sebelum ibadah.",body:`<p>Wuduk ialah cara bersuci yang dilakukan dengan menggunakan air pada anggota tertentu. Antara perkara asas yang perlu dipelajari ialah niat, membasuh muka, tangan hingga siku, menyapu kepala dan membasuh kaki mengikut kaedah yang sah.</p><p>Perincian rukun, sunat dan perkara yang membatalkan wuduk boleh berbeza mengikut mazhab. Rujuk guru atau sumber agama yang berautoriti untuk panduan amali.</p>`},
{id:"solat",title:"Solat",intro:"Pengenalan kepada solat fardu lima waktu.",body:`<p>Solat fardu dilaksanakan lima kali sehari: Subuh, Zohor, Asar, Maghrib dan Isyak. Setiap solat mempunyai waktu, bilangan rakaat dan rukun yang perlu dipelajari.</p><p>Untuk memastikan bacaan dan pergerakan dilakukan dengan betul, belajar secara amali bersama guru yang berkelayakan.</p>`},
{id:"quran-adab",title:"Adab Membaca Al-Quran",intro:"Beberapa adab asas ketika membaca Al-Quran.",body:`<ul><li>Menjaga kebersihan dan kesopanan.</li><li>Membaca dengan tenang dan memberi perhatian.</li><li>Berusaha membaca dengan tartil dan sebutan yang baik.</li><li>Memahami makna ayat melalui terjemahan atau huraian yang sahih.</li><li>Menghormati Al-Quran dan tidak membacanya secara sambil lewa.</li></ul>`},
{id:"sedekah",title:"Sedekah",intro:"Pengenalan kepada amalan memberi.",body:`<p>Sedekah ialah amalan memberi manfaat kepada orang lain kerana Allah. Ia tidak terhad kepada wang; bantuan, makanan, masa dan kebaikan kepada orang lain juga boleh menjadi amalan yang bernilai.</p><p>Lakukan mengikut kemampuan dan utamakan niat yang ikhlas.</p>`}
];
const DAILY=[
["Belajar sedikit, faham sedikit","Gunakan satu minit hari ini untuk mengulang satu perkara asas yang telah dipelajari."],["Solat tepat pada waktunya","Semak Waktu Solat dan gunakan peringatan sebagai bantuan mengurus masa ibadah."],["Baca dengan tenang","Apabila membaca Al-Quran, beri perhatian kepada bacaan dan cuba fahami maksud melalui terjemahan yang tersedia."],["Mulakan dengan konsisten","Amalan kecil yang dibuat secara teratur boleh membantu membina rutin pembelajaran."],["Belajar dengan guru","Untuk bacaan, ibadah dan fiqh yang terperinci, dapatkan bimbingan daripada guru atau sumber berautoriti."]];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state=defaultState(),clockTimer=null,notificationTimer=null,surahs=[],currentSurah=null,currentSurahNumber=0,playlistIndex=0,audioUrls=[],lastRenderedPrayerName="",prayerRequest=null,orientationLast=0;
const KAABA={lat:21.422487,lon:39.826206};
function defaultState(){return{profile:{name:""},bookmarks:[],ayahBookmarks:[],notes:{},lastRead:null,dhikr:{selected:"subhanallah"},learning:{},location:null,preferences:{theme:"dark",notificationMode:"off",notificationSound:"azan",haptic:true,reducedData:false,quranFont:31,quranTranslation:"ms.basmeih",fontScale:1,highContrast:false,autoNext:true,repeatAyah:false,playbackRate:1},daily:{streak:0,lastDay:null,prayers:{},history:{}},quranPlan:{target:2,days:{},totalDays:0},ramadan:{checklist:{},note:""},setupDone:false}};
function loadState(){try{const keys=[C.storageKey,"NUR_ACADEMY_V13","NUR_ACADEMY_V12"];let raw=null;for(const k of keys){raw=localStorage.getItem(k);if(raw)break}if(!raw)return;const p=JSON.parse(raw);state=defaultState();state.profile=Object.assign({},state.profile,p.profile||{});state.preferences=Object.assign({},state.preferences,p.preferences||{});state.dhikr=Object.assign({},state.dhikr,p.dhikr||{});state.learning=p.learning&&typeof p.learning==="object"?p.learning:{};state.bookmarks=Array.isArray(p.bookmarks)?p.bookmarks:[];state.ayahBookmarks=Array.isArray(p.ayahBookmarks)?p.ayahBookmarks:[];state.notes=p.notes&&typeof p.notes==="object"?p.notes:{};state.lastRead=p.lastRead||null;state.location=p.location||null;state.daily=Object.assign({},state.daily,p.daily||{});state.daily.history=state.daily.history&&typeof state.daily.history==="object"?state.daily.history:{};state.quranPlan=Object.assign({},state.quranPlan,p.quranPlan||{});state.quranPlan.days=state.quranPlan.days&&typeof state.quranPlan.days==="object"?state.quranPlan.days:{};state.ramadan=Object.assign({},state.ramadan,p.ramadan||{});state.ramadan.checklist=state.ramadan.checklist&&typeof state.ramadan.checklist==="object"?state.ramadan.checklist:{};state.setupDone=Boolean(p.setupDone);saveState()}catch(e){state=defaultState();try{localStorage.removeItem(C.storageKey)}catch(_){} }}
function saveState(){try{localStorage.setItem(C.storageKey,JSON.stringify(state));}catch(e){toast("Data tidak dapat disimpan pada peranti ini.")}}
function toast(msg,target="#settingsMessage"){const el=$(target);if(el){el.textContent=msg;window.clearTimeout(el._toastTimer);el._toastTimer=window.setTimeout(()=>{if(el.textContent===msg)el.textContent=""},3500)}}
function showPage(name){const valid=["utama","solat","quran","reader","zikir","akademi","kiblat","search","tetapan","ramadan","tentang","privasi","terma","sumber","bantuan"];if(!valid.includes(name))name="utama";$$('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${name}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.go===name||(name==='reader'&&b.dataset.go==='quran')));history.replaceState(null,"",`#${name}`);window.scrollTo({top:0,behavior:'auto'});if(name==='quran'&&!surahs.length)loadSurahs();if(name==='kiblat')renderQiblaUpgraded();if(name==='ramadan')renderRamadan();if(name==='utama')renderHome();if(name==='search')runGlobalSearch($('#globalSearch')?.value||'')}
function setupSideMenu(){const menu=$('#sideMenu'),overlay=$('#menuOverlay'),open=$('#menuBtn'),close=$('#closeMenuBtn');const set=v=>{menu.classList.toggle('open',v);menu.setAttribute('aria-hidden',String(!v));open.setAttribute('aria-expanded',String(v));overlay.hidden=!v;document.body.classList.toggle('menu-open',v)};open.onclick=()=>set(true);close.onclick=()=>set(false);overlay.onclick=()=>set(false);menu.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b){set(false);showPage(b.dataset.go)}});$('#sideSearchBtn').onclick=()=>{set(false);$('#globalSearch').value=$('#globalSearchSide').value;showPage('search');runGlobalSearch($('#globalSearch').value)};document.addEventListener('keydown',e=>{if(e.key==='Escape')set(false)})}
function setupNavigation(){document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go){e.preventDefault();showPage(go.dataset.go)}});$('#quickSearchBtn').onclick=()=>showPage('search')}
function updateClock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('ms-MY',{hour12:false});$('#dateText').textContent=d.toLocaleDateString('ms-MY',{weekday:'long',day:'numeric',month:'long',year:'numeric'});renderCalendarDates(d);updateCountdown()}
function localDateKey(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function prayerDate(time,offset=0){const [h,m]=String(time).split(':').map(Number);const d=new Date();d.setHours(Number.isFinite(h)?h:0,Number.isFinite(m)?m:0,0,0);d.setDate(d.getDate()+offset);return d}
function getPrayerEntries(){if(!state.location?.timings)return[];return PRAYERS.map(([api,name])=>({api,name,time:state.location.timings[api]})).filter(x=>/^\d{1,2}:\d{2}$/.test(x.time))}
function nextPrayer(){const entries=getPrayerEntries();if(!entries.length)return null;const now=new Date();for(const p of entries){const date=prayerDate(p.time);if(date>now)return{...p,date,dayOffset:0}}const first=entries[0];return{...first,date:prayerDate(first.time,1),dayOffset:1}}
function updateCountdown(){const next=nextPrayer();if(!next){$('#countdown').textContent='—';$('#homeCountdown').textContent='—';$('#nextPrayerName').textContent='—';$('#homeNextPrayer').textContent='—';if(lastRenderedPrayerName!=='') {renderPrayerRows();lastRenderedPrayerName='';}return}const sec=Math.max(0,Math.floor((next.date-Date.now())/1000)),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60,text=[h,m,s].map(v=>String(v).padStart(2,'0')).join(':');$('#countdown').textContent=text;$('#homeCountdown').textContent=text;$('#nextPrayerName').textContent=next.name;$('#homeNextPrayer').textContent=next.name;if(lastRenderedPrayerName!==next.name){renderPrayerRows(next);lastRenderedPrayerName=next.name;}}
function renderPrayerRows(next=null){const box=$('#prayerList'),entries=getPrayerEntries();if(!entries.length){box.innerHTML='<div class="loading">Waktu solat belum tersedia.</div>';return}box.innerHTML=entries.map(p=>{const done=Boolean(state.daily?.prayers?.[p.name]);return `<button type="button" class="prayer-row ${next&&p.name===next.name?'active ':''}${done?'completed':''}" data-prayer="${escapeHtml(p.name)}" aria-pressed="${done}"><div><strong>${escapeHtml(p.name)}</strong><small>${p.api}${done?' · Selesai':''}</small></div><time>${escapeHtml(p.time)}</time></button>`}).join('')}
function setLocation(lat,lon,label,type){const nlat=Number(lat),nlon=Number(lon);if(!Number.isFinite(nlat)||!Number.isFinite(nlon))return false;state.location={lat:nlat,lon:nlon,label:String(label||'Lokasi'),type:type||'manual',timings:null,dateKey:null};saveState();updateLocationUI();return true}
async function fetchPrayerTimes(){
if(prayerRequest)return prayerRequest;
if(!state.location||!Number.isFinite(Number(state.location.lat))||!Number.isFinite(Number(state.location.lon))){renderPrayerRows();return false}
const previous=state.location.timings;
if(!previous)$('#prayerList').innerHTML='<div class="loading">Memuatkan waktu solat…</div>';
const run=async()=>{const controller=new AbortController(),timeout=window.setTimeout(()=>controller.abort(),7000);try{const d=new Date(),url=`${C.prayerApi}/timings/${Math.floor(d.getTime()/1000)}?latitude=${encodeURIComponent(state.location.lat)}&longitude=${encodeURIComponent(state.location.lon)}&method=${C.prayerMethod}`;const res=await fetch(url,{headers:{Accept:'application/json'},signal:controller.signal,cache:'no-store'});if(!res.ok)throw new Error('Prayer API');const data=await res.json(),timings=data?.data?.timings;if(!timings)throw new Error('Invalid prayer data');state.location.timings=Object.fromEntries(PRAYERS.map(([k])=>[k,String(timings[k]||'').slice(0,5)]));state.location.dateKey=localDateKey(d);saveState();lastRenderedPrayerName='';renderPrayerRows(nextPrayer());updateCountdown();toast('Waktu solat berjaya dimuatkan.','#locationMessage');return true}catch(e){if(previous){renderPrayerRows(nextPrayer());updateCountdown();toast('Sambungan lambat. Menggunakan waktu solat terakhir yang tersimpan.','#locationMessage')}else{$('#prayerList').innerHTML='<div class="error-box">Data waktu solat tidak dapat dimuatkan sekarang.</div><button id="retryPrayerInline" class="btn secondary full">Cuba lagi</button>'}return false}finally{window.clearTimeout(timeout)}};prayerRequest=run();try{return await prayerRequest}finally{prayerRequest=null}}
async function geocodeCity(city,target='#locationMessage'){toast('Mencari lokasi…',target);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),7000);try{const res=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=my&q=${encodeURIComponent(city)}`,{headers:{Accept:'application/json'},signal:controller.signal,cache:'no-store'});if(!res.ok)throw new Error('Geocoding gagal');const data=await res.json();if(!Array.isArray(data)||!data.length)throw new Error('Lokasi tidak ditemui');const ok=setLocation(Number(data[0].lat),Number(data[0].lon),data[0].display_name||city,'manual');if(!ok)throw new Error('Koordinat tidak sah');updateLocationUI();await fetchPrayerTimes();renderQibla();toast('Lokasi berjaya digunakan.','#locationMessage');if(target!=='#locationMessage')toast('Lokasi berjaya digunakan.',target);return true}catch(e){toast(e?.name==='AbortError'?'Carian lokasi mengambil masa terlalu lama.':'Lokasi bandar tidak ditemui. Cuba nama bandar yang lain.',target);return false}finally{clearTimeout(timer)}}
function setupLocation(){
$('#useGpsBtn').onclick=()=>useGps('#locationMessage');
$('#qiblaGpsBtn').onclick=()=>useGps('#qiblaMessage');
$('#qiblaRefreshBtn').onclick=renderQiblaUpgraded;
$('#manualLocationBtn').onclick=()=>openManualLocation();
$('#refreshPrayerBtn').onclick=fetchPrayerTimes;
$('#prayerList').addEventListener('click',e=>{if(e.target.id==='retryPrayerInline')fetchPrayerTimes()});
}
async function useGps(targetMessage='#locationMessage'){const report=msg=>toast(msg,targetMessage);if(!window.isSecureContext){report('Lokasi hanya boleh digunakan melalui sambungan selamat. Jika anda membuka fail ZIP terus, gunakan laman HTTPS.');return false}if(!navigator.geolocation){report('Peranti ini tidak menyediakan lokasi. Gunakan pilihan bandar manual.');return false}try{if(navigator.permissions?.query){const perm=await navigator.permissions.query({name:'geolocation'});if(perm.state==='denied'){report('Akses lokasi sedang disekat. Benarkan lokasi untuk laman ini dalam tetapan pelayar, kemudian cuba lagi.');return false}}}catch(_){}report('Mengesan lokasi peranti…');const get=opts=>new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,opts));try{let pos;try{pos=await get({enableHighAccuracy:true,timeout:15000,maximumAge:120000})}catch(first){if(first?.code===1)throw first;pos=await get({enableHighAccuracy:false,timeout:10000,maximumAge:600000})}const ok=setLocation(pos.coords.latitude,pos.coords.longitude,'Lokasi peranti','gps');if(!ok)throw new Error('invalid');updateLocationUI();report('Lokasi berjaya digunakan.');await fetchPrayerTimes();renderQibla();if(targetMessage==='#qiblaMessage')$('#qiblaMessage').textContent='Lokasi peranti berjaya digunakan. Bearing dikira semula.';return true}catch(err){const msg=err?.code===1?'Akses lokasi ditolak. Benarkan Location untuk laman ini dan cuba lagi.':err?.code===2?'Lokasi belum dapat dikesan. Pastikan Location/GPS dihidupkan, kemudian cuba lagi.':'Lokasi mengambil masa terlalu lama. Cuba lagi atau gunakan bandar manual.';report(msg);return false}}
function openManualLocation(){const modal=$('#setupModal');if(!modal.hidden){$('#setupCity').focus();return}const city=window.prompt('Masukkan bandar, contohnya Kuching:');if(city?.trim())geocodeCity(city.trim())}
function setupNotifications(){$('#notificationMode').value=state.preferences.notificationMode||'off';$('#notificationMode').onchange=()=>{state.preferences.notificationMode=$('#notificationMode').value;saveState()};$('#notificationBtn').onclick=async()=>{if(!('Notification' in window)){toast('Pelayar ini tidak menyokong notifikasi.','#locationMessage');return}const p=await Notification.requestPermission();if(p==='granted'){if(state.preferences.notificationMode==='off')state.preferences.notificationMode='0';$('#notificationMode').value=state.preferences.notificationMode;saveState();toast('Kebenaran notifikasi telah diberikan.','#locationMessage')}else toast('Kebenaran notifikasi tidak diberikan.','#locationMessage')};$('#testNotificationBtn').onclick=()=>{showNotification('NUR Academy','Ini ialah notifikasi ujian waktu solat.');playBuiltInSound(state.preferences.notificationSound).catch(()=>{})}}
function showNotification(title,body){if(!('Notification'in window)||Notification.permission!=='granted')return;try{new Notification(title,{body,icon:'./assets/nur-academy-logo.png',tag:'nur-academy-test'})}catch(_){}}
function checkPrayerNotification(){const mode=state.preferences.notificationMode;if(mode==='off')return;const next=nextPrayer();if(!next)return;const offset=Number(mode);const diff=Math.round((next.date-Date.now())/60000);if(diff!==offset)return;const key=`${localDateKey(next.date)}-${next.name}-${offset}`;try{if(localStorage.getItem('NUR_NOTIF_'+key))return;localStorage.setItem('NUR_NOTIF_'+key,'1')}catch(_){}showNotification(`Waktu ${next.name}`,offset?`${next.name} akan masuk dalam ${offset} minit.`:`Sudah masuk waktu ${next.name}.`);playBuiltInSound(state.preferences.notificationSound).catch(()=>{})}
function playBuiltInSound(type='azan'){if(type==='none')return Promise.resolve();const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return Promise.reject(new Error('AudioContext tidak disokong'));const ctx=new AC(),now=ctx.currentTime,seq=type==='azan'?[440,494,523,587,659,587,523,494,440]:type==='classic'?[523,659,784,659,523]:[392,440,494,440,392];const gain=ctx.createGain();gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.12,now+.03);gain.gain.exponentialRampToValueAtTime(.0001,now+Math.min(4,seq.length*.45+.2));gain.connect(ctx.destination);seq.forEach((f,i)=>{const o=ctx.createOscillator();o.type='sine';o.frequency.value=f;o.connect(gain);o.start(now+i*.45);o.stop(now+i*.45+.38)});return new Promise(resolve=>setTimeout(()=>{ctx.close();resolve()},Math.min(4200,seq.length*450+300)))}
function setupAudio(){const select=$('#notificationSound');select.value=state.preferences.notificationSound||'azan';select.onchange=()=>{state.preferences.notificationSound=select.value;saveState();toast('Bunyi notifikasi berjaya ditetapkan.','#audioMessage')};$('#testAudioBtn').onclick=()=>playBuiltInSound(select.value).then(()=>toast('Bunyi berjaya diuji.','#audioMessage')).catch(()=>toast('Bunyi tidak dapat dimainkan pada pelayar ini.','#audioMessage'))}
async function loadSurahs(){if(surahs.length){renderSurahs($('#surahSearch').value);return}$('#surahList').innerHTML='<div class="loading">Memuatkan senarai surah…</div>';$('#quranError').classList.add('hidden');try{const res=await fetch(`${C.quranApi}/surah`);if(!res.ok)throw 0;const data=await res.json();if(!Array.isArray(data?.data)||data.data.length!==114)throw 0;surahs=data.data;renderSurahs()}catch(e){$('#surahList').innerHTML='';$('#quranError').classList.remove('hidden');$('#quranError').innerHTML='Data Al-Quran tidak dapat dimuatkan sekarang.<br><button id="retryQuran" class="btn secondary">Cuba lagi</button>'}}
function normalizeSearch(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
function renderSurahs(filter=''){const f=normalizeSearch(filter);const list=surahs.filter(s=>!f||String(s.number)===f||normalizeSearch(`${s.englishName} ${s.name} ${s.englishNameTranslation}`).includes(f));if(!list.length){$('#surahList').innerHTML='<div class="loading">Surah tidak ditemui.</div>';return}$('#surahList').innerHTML=list.map(s=>`<button class="surah-item" data-surah="${s.number}"><span class="surah-num">${s.number}</span><span><strong>${escapeHtml(s.englishName)}</strong><small>${escapeHtml(s.englishNameTranslation||'')} · ${s.numberOfAyahs} ayat</small></span><span class="bookmark">${state.bookmarks.includes(s.number)?'Disimpan':'→'}</span></button>`).join('');$('#bookmarkCount').textContent=`${state.ayahBookmarks.length} ayat`;$('#bookmarkPanel').classList.toggle('hidden',state.ayahBookmarks.length===0)}
async function openSurah(number,focusAyah=0){showPage('reader');$('#ayahList').innerHTML='<div class="loading">Memuatkan surah…</div>';$('#quranAudio').removeAttribute('src');audioUrls=[];playlistIndex=0;currentSurahNumber=number;try{const res=await fetch(`${C.quranApi}/surah/${number}/editions/quran-uthmani,${encodeURIComponent(state.preferences.quranTranslation||"ms.basmeih")},ar.alafasy`);if(!res.ok)throw 0;const data=await res.json();if(!Array.isArray(data?.data)||data.data.length<3)throw 0;const arabic=data.data.find(x=>x.edition?.identifier==='quran-uthmani'),trans=data.data.find(x=>x.edition?.identifier===(state.preferences.quranTranslation||'ms.basmeih')),audio=data.data.find(x=>x.edition?.identifier==='ar.alafasy');if(!arabic||!trans||!audio)throw 0;if(!Array.isArray(arabic.ayahs)||!arabic.ayahs.length)throw 0;currentSurah=arabic;audioUrls=Array.isArray(audio.ayahs)?audio.ayahs.map(a=>a.audio).filter(Boolean):[];$('#readerMeta').textContent=`Surah ${number}`;$('#readerTitle').textContent=arabic.name||'';$('#readerSubtitle').textContent=`${arabic.englishName||''} · ${arabic.numberOfAyahs} ayat · ${trans?.edition?.englishName||'Terjemahan'}`;
$('#bookmarkBtn').textContent=state.bookmarks.includes(number)?'Disimpan':'Simpan Surah';const tr=trans.ayahs||[];$('#ayahList').innerHTML=arabic.ayahs.map((a,i)=>{const key=`${number}:${a.numberInSurah}`,saved=state.ayahBookmarks.some(x=>x.key===key);return `<article class="ayah" id="ayah-${a.numberInSurah}" data-ayah="${a.numberInSurah}"><div class="ayah-head"><span>Ayat ${a.numberInSurah}</span><span>${audioUrls[i]?'Audio tersedia':'Audio tidak tersedia'}</span></div><div class="arabic" lang="ar" dir="rtl">${escapeHtml(a.text)}</div><div class="translation">${escapeHtml(tr[i]?.text||'Terjemahan tidak tersedia.')}</div><div class="ayah-actions">${audioUrls[i]?`<button class="mini-btn play-ayah" data-index="${i}">Dengar</button>`:''}<button class="mini-btn bookmark-ayah" data-index="${i}">${saved?'Disimpan':'Simpan Ayat'}</button><button class="mini-btn note-ayah" data-index="${i}">${state.notes[key]?'Edit Nota':'Nota'}</button></div></article>`}).join('');if(focusAyah>0)document.getElementById(`ayah-${focusAyah}`)?.scrollIntoView({behavior:'smooth',block:'center'});renderReaderPlaying()}
catch(e){$('#ayahList').innerHTML='<div class="error-box">Surah tidak dapat dimuatkan. Internet diperlukan untuk membaca kandungan ini.<br><button id="retrySurah" class="btn secondary">Cuba lagi</button></div>'}}
function setupQuran(){$('#surahSearch').oninput=e=>renderSurahs(e.target.value);$('#surahList').onclick=e=>{const saved=e.target.closest('[data-bookmark-surah]');if(saved){openSurah(Number(saved.dataset.bookmarkSurah),Number(saved.dataset.bookmarkAyah));return}const b=e.target.closest('[data-surah]');if(b)openSurah(Number(b.dataset.surah))};$('#quranError').onclick=e=>{if(e.target.id==='retryQuran')loadSurahs()};$('#ayahList').onclick=e=>{const b=e.target.closest('.play-ayah');if(b){playAyah(Number(b.dataset.index));return}const bm=e.target.closest('.bookmark-ayah');if(bm){toggleAyahBookmark(Number(bm.dataset.index));return}const nt=e.target.closest('.note-ayah');if(nt)openNote(Number(nt.dataset.index))};$('#bookmarkBtn').onclick=()=>{if(!currentSurah)return;const n=currentSurah.number;if(state.bookmarks.includes(n))state.bookmarks=state.bookmarks.filter(x=>x!==n);else state.bookmarks.push(n);saveState();$('#bookmarkBtn').textContent=state.bookmarks.includes(n)?'Disimpan':'Simpan Surah';renderSurahs($('#surahSearch').value)};$('#playSurahBtn').onclick=()=>{if(!audioUrls.length){toast('Audio surah tidak tersedia.','#audioStatus');return}playAyah(playlistIndex||0)};$('#quranAudio').onended=()=>{if(state.preferences.repeatAyah){playAyah(playlistIndex);return}if(state.preferences.autoNext){const next=playlistIndex+1;if(next<audioUrls.length){playAyah(next);return}if(currentSurahNumber<114){openSurah(currentSurahNumber+1,1);return}}$('#audioStatus').textContent='Bacaan selesai.';renderReaderPlaying()};$('#autoNextToggle').onchange=e=>{state.preferences.autoNext=e.target.checked;saveState()};$('#repeatAyahToggle').onchange=e=>{state.preferences.repeatAyah=e.target.checked;saveState()};$('#playbackRate').onchange=e=>{state.preferences.playbackRate=Number(e.target.value)||1;$('#quranAudio').playbackRate=state.preferences.playbackRate;saveState()};$('#fullscreenReaderBtn').onclick=()=>{const el=$('#page-reader');if(!document.fullscreenElement)el.requestFullscreen?.();else document.exitFullscreen?.()};$('#showBookmarksBtn').onclick=showBookmarkedAyahs;setupQuranExplore()}
function playAyah(i){if(!audioUrls[i]){toast('Audio ayat ini tidak tersedia.','#audioStatus');return}playlistIndex=i;const a=$('#quranAudio');a.src=audioUrls[i];a.playbackRate=Number(state.preferences.playbackRate||1);const ay=currentSurah?.ayahs?.[i];if(ay){state.lastRead={surah:currentSurah.number,ayah:ay.numberInSurah,name:currentSurah.englishName||currentSurah.name};saveState();renderHome()}a.play().then(()=>{$('#audioStatus').textContent=`Sedang membaca ayat ${ay?.numberInSurah||i+1}.`;renderReaderPlaying();document.getElementById(`ayah-${ay?.numberInSurah||i+1}`)?.scrollIntoView({behavior:'smooth',block:'center'})}).catch(()=>{$('#audioStatus').textContent='Tekan Play pada pemain audio untuk memulakan bacaan.';renderReaderPlaying()})}
function renderReaderPlaying(){$$('.ayah').forEach((el,i)=>el.classList.toggle('playing',i===playlistIndex))}
function toggleAyahBookmark(i){const ay=currentSurah?.ayahs?.[i];if(!ay)return;const key=`${currentSurah.number}:${ay.numberInSurah}`,idx=state.ayahBookmarks.findIndex(x=>x.key===key);if(idx>=0)state.ayahBookmarks.splice(idx,1);else state.ayahBookmarks.push({key,surah:currentSurah.number,ayah:ay.numberInSurah,name:currentSurah.englishName||currentSurah.name});saveState();openSurah(currentSurah.number,ay.numberInSurah)}
function showBookmarkedAyahs(){if(!state.ayahBookmarks.length){toast('Belum ada ayat yang disimpan.');return}const html=state.ayahBookmarks.map(x=>`<button class="search-result" data-bookmark-surah="${x.surah}" data-bookmark-ayah="${x.ayah}"><strong>${escapeHtml(x.name||`Surah ${x.surah}`)} · Ayat ${x.ayah}</strong><small>Buka ayat simpanan</small></button>`).join('');$('#surahList').innerHTML=html}
function openNote(i){const ay=currentSurah?.ayahs?.[i];if(!ay)return;const key=`${currentSurah.number}:${ay.numberInSurah}`;$('#noteModal').dataset.key=key;$('#noteModal').dataset.index=String(i);$('#noteTitle').textContent=`Nota Ayat ${ay.numberInSurah}`;$('#noteText').value=state.notes[key]||'';$('#noteMessage').textContent='';$('#noteModal').hidden=false;$('#noteText').focus()}
function setupNotes(){$('#closeNoteBtn').onclick=()=>$('#noteModal').hidden=true;$('#saveNoteBtn').onclick=()=>{const key=$('#noteModal').dataset.key,text=$('#noteText').value.trim();if(text)state.notes[key]=text;else delete state.notes[key];saveState();$('#noteModal').hidden=true;openSurah(currentSurahNumber,Number($('#noteModal').dataset.index||0))};$('#deleteNoteBtn').onclick=()=>{const key=$('#noteModal').dataset.key;delete state.notes[key];saveState();$('#noteModal').hidden=true;openSurah(currentSurahNumber,Number($('#noteModal').dataset.index||0))}}
function setupDhikr(){const box=$('#dhikrChoices');box.innerHTML=DHIKR.map(d=>`<button class="choice-card" data-dhikr="${d.id}"><strong>${d.name}</strong><small>${d.target} kali</small></button>`).join('');box.onclick=e=>{const b=e.target.closest('[data-dhikr]');if(b){state.dhikr.selected=b.dataset.dhikr;saveState();renderDhikr();renderUpgradeDashboard()}};$('#dhikrAddBtn').onclick=()=>{const d=DHIKR.find(x=>x.id===state.dhikr.selected)||DHIKR[0],n=Math.min(Number(state.dhikr.target||d.target),Number(state.dhikr[d.id]||0)+1);state.dhikr[d.id]=n;state.dhikr.completedToday=state.dhikr.completedToday||{};if(n>=Number(state.dhikr.target||d.target))state.dhikr.completedToday[localDateKey()]=true;saveState();renderDhikr();renderHome();renderUpgradeDashboard()};$('#dhikrResetBtn').onclick=()=>{const d=DHIKR.find(x=>x.id===state.dhikr.selected)||DHIKR[0];state.dhikr[d.id]=0;state.dhikr.completedToday=state.dhikr.completedToday||{};delete state.dhikr.completedToday[localDateKey()];saveState();renderDhikr();renderHome();renderUpgradeDashboard()};$$('[data-dhikr-target]').forEach(b=>b.onclick=()=>{state.dhikr.target=Number(b.dataset.dhikrTarget);saveState();renderDhikr()});renderDhikr()}
function renderDhikr(){const d=DHIKR.find(x=>x.id===state.dhikr.selected)||DHIKR[0],target=Number(state.dhikr.target||d.target),n=Math.min(target,Number(state.dhikr[d.id]||0));$$('[data-dhikr]').forEach(b=>b.classList.toggle('selected',b.dataset.dhikr===d.id));$$('[data-dhikr-target]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.dhikrTarget)===target));$('#dhikrName').textContent=d.name;$('#dhikrCount').textContent=`${n} / ${target}`;$('#dhikrProgress').style.width=`${n/target*100}%`;$('#dhikrRoutineText').textContent=`Target semasa: ${target} kali · ${n>=target?'Selesai untuk sesi ini.':'Boleh diteruskan sekarang.'}`}
const QUIZZES={islam:[['Berapakah Rukun Islam?',['3','5','6'],1],['Yang manakah termasuk Rukun Islam?',['Syahadah','Percaya kepada malaikat','Percaya kepada kitab'],0]],iman:[['Berapakah Rukun Iman?',['4','5','6'],2],['Yang manakah termasuk Rukun Iman?',['Solat','Hari Akhirat','Zakat'],1]],wuduk:[['Wuduk digunakan untuk apa?',['Bersuci sebelum ibadah tertentu','Menggantikan semua ibadah','Mengira rakaat'],0]],solat:[['Berapakah solat fardu dalam sehari?',['3','5','7'],1]],'quran-adab':[['Bagaimana sebaiknya membaca Al-Quran?',['Dengan tenang dan tartil','Sambil lewa','Tanpa perhatian'],0]],sedekah:[['Sedekah hanya bermaksud wang?',['Ya','Tidak'],1]]};
function setupAcademy(){const grid=$('#lessonGrid');if(grid)grid.innerHTML='';const reader=$('#lessonReader');if(reader)reader.classList.add('hidden');const quiz=$('#quizPanel');if(quiz)quiz.classList.add('hidden');renderUpgradeDashboard()}
function setupSettings(){$('#displayName').value=state.profile.name||'';$('#saveNameBtn').onclick=()=>{state.profile.name=$('#displayName').value.trim();saveState();toast('Nama paparan berjaya disimpan.');renderHome()};$$('.theme-btn').forEach(b=>b.onclick=()=>{state.preferences.theme=b.dataset.theme;saveState();applyTheme()});const fs=$('#fontScaleSelect');if(fs){fs.value=String(state.preferences.fontScale||1);fs.onchange=()=>{state.preferences.fontScale=Number(fs.value);saveState();applyTheme()}}const hc=$('#highContrastToggle');if(hc){hc.checked=!!state.preferences.highContrast;hc.onchange=()=>{state.preferences.highContrast=hc.checked;saveState();applyTheme()}}$('#clearDataBtn').onclick=()=>{if(confirm('Padam semua data NUR Academy pada peranti ini?')){try{localStorage.removeItem(C.storageKey)}catch(_){}state=defaultState();applyTheme();$('#displayName').value='';renderDhikr();renderHome();renderUpgradeDashboard();toast('Semua data telah dipadam.')}};const ex=$('#exportDataBtn');if(ex)ex.onclick=exportData;const im=$('#importDataInput');if(im)im.onchange=importData;setupRamadan();setupQuranPlan()}
function applyTheme(){document.body.classList.toggle('light',state.preferences.theme==='light');document.body.classList.toggle('high-contrast',!!state.preferences.highContrast);document.body.style.setProperty('--app-scale',String(state.preferences.fontScale||1));$$('.theme-btn').forEach(b=>b.classList.toggle('active',b.dataset.theme===state.preferences.theme))}
function updateLocationUI(){const l=state.location?.label||'Belum ditetapkan';$('#homeLocation').textContent=l;$('#prayerLocation').textContent=l;$('#locationType').textContent=state.location?.type==='gps'?'Peranti':state.location?.type==='manual'?'Manual':'—';renderPrayerRows(nextPrayer());renderQibla()}
function bearing(lat1,lon1,lat2,lon2){const r=Math.PI/180,a1=lat1*r,a2=lat2*r,dl=(lon2-lon1)*r;const y=Math.sin(dl)*Math.cos(a2),x=Math.cos(a1)*Math.sin(a2)-Math.sin(a1)*Math.cos(a2)*Math.cos(dl);return(Math.atan2(y,x)/r+360)%360}
function direction(deg){const dirs=['Utara','Timur Laut','Timur','Tenggara','Selatan','Barat Daya','Barat','Barat Laut'];return dirs[Math.round(deg/45)%8]}
function renderQibla(){const el=$('#qiblaDegrees');if(!el)return;if(!state.location){el.textContent='—°';$('#qiblaDirection').textContent='Tetapkan lokasi untuk mengira arah';$('#qiblaVisual .qibla-arrow').style.transform='rotate(0deg)';$('#headingReadout').textContent='Kompas belum diaktifkan';return}const deg=bearing(Number(state.location.lat),Number(state.location.lon),KAABA.lat,KAABA.lon);el.textContent=`${deg.toFixed(1)}°`;$('#qiblaDirection').textContent=direction(deg);$('#qiblaVisual .qibla-arrow').style.transform=`rotate(${deg}deg)`;$('#qiblaMessage').textContent=`Lokasi: ${state.location.label}. Bearing dikira secara geografi.`}
function hijriParts(d){try{const parts=new Intl.DateTimeFormat('en-US-u-ca-islamic-umalqura',{year:'numeric',month:'numeric',day:'numeric'}).formatToParts(d);return{year:Number(parts.find(x=>x.type==='year')?.value),month:Number(parts.find(x=>x.type==='month')?.value),day:Number(parts.find(x=>x.type==='day')?.value)}}catch(_){return{year:0,month:0,day:0}}}
function renderCalendarDates(d){const normal=d.toLocaleDateString('ms-MY',{weekday:'long',day:'numeric',month:'long',year:'numeric'});let h='Tarikh Islam tidak tersedia';try{h=new Intl.DateTimeFormat('ms-MY-u-ca-islamic-umalqura',{day:'numeric',month:'long',year:'numeric'}).format(d)}catch(_){}$('#dateText').textContent=normal;$('#hijriDateText').textContent=`Tarikh Islam · ${h}`}
function findNextRamadan(){const now=new Date();for(let i=0;i<500;i++){const d=new Date(now);d.setDate(now.getDate()+i);const h=hijriParts(d);if(h.month===9)return{date:d,parts:h}}return null}
function renderRamadan(){const now=new Date(),h=hijriParts(now),next=findNextRamadan();if(h.month===9){$('#ramadanStatus').textContent=`Ramadan ${h.year} sedang berlangsung`;$('#ramadanDayBadge').textContent=`Hari ${h.day}`;$('#ramadanCountdown').textContent='Teruskan rutin Ramadan hari ini.'}else if(next){const days=Math.ceil((next.date.setHours(0,0,0,0)-new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime())/86400000);$('#ramadanStatus').textContent=`Menuju Ramadan ${next.parts.year}`;$('#ramadanDayBadge').textContent=`${days} hari`;$('#ramadanCountdown').textContent=`Anggaran berdasarkan kalendar Umm al-Qura pada peranti.`}$('#ramadanImsak').textContent=state.location?.timings?.Imsak||'—';$('#ramadanIftar').textContent=state.location?.timings?.Maghrib||'—';const items=[['prayer','Jaga solat lima waktu'],['quran','Baca Al-Quran'],['dhikr','Zikir / doa harian'],['charity','Sedekah atau bantu orang lain'],['learning','Belajar ilmu Islam']];const day=localDateKey();const current=state.ramadan.checklist[day]||{};$('#ramadanChecklist').innerHTML=items.map(([id,label])=>`<label class="check-row"><input type="checkbox" data-ramadan="${id}" ${current[id]?'checked':''}><span>${label}</span></label>`).join('');const done=items.filter(x=>current[x[0]]).length;$('#ramadanDone').textContent=`${done}/${items.length}`;$('#ramadanProgress').style.width=`${done/items.length*100}%`;$('#ramadanNote').value=state.ramadan.note||''}
function setupRamadan(){const box=$('#ramadanChecklist');if(box){box.onclick=e=>{const i=e.target.closest('[data-ramadan]');if(!i)return;const day=localDateKey();state.ramadan.checklist[day]=state.ramadan.checklist[day]||{};state.ramadan.checklist[day][i.dataset.ramadan]=i.checked;saveState();renderRamadan()}}$('#saveRamadanNote').onclick=()=>{state.ramadan.note=$('#ramadanNote').value.trim();saveState();toast('Catatan Ramadan disimpan.','#ramadanMessage')};renderRamadan()}
function setupQuranPlan(){const sel=$('#quranPlanTarget'),btn=$('#quranPlanTodayBtn');if(!sel||!btn)return;sel.value=String(state.quranPlan.target||2);sel.onchange=()=>{state.quranPlan.target=Number(sel.value);saveState();renderQuranPlan()};btn.onclick=()=>{state.quranPlan.days[localDateKey()]=true;state.quranPlan.totalDays=Object.values(state.quranPlan.days).filter(Boolean).length;saveState();renderQuranPlan();toast('Rutin bacaan hari ini ditanda selesai.','#quranPlanText')};renderQuranPlan()}
function renderQuranPlan(){const sel=$('#quranPlanTarget');if(!sel)return;const target=Number(state.quranPlan.target||2),done=Boolean(state.quranPlan.days[localDateKey()]),total=Object.values(state.quranPlan.days||{}).filter(Boolean).length;$('#quranPlanPercent').textContent=`${Math.min(100,Math.round(done?100:0))}%`;$('#quranPlanBar').style.width=`${done?100:0}%`;$('#quranPlanText').textContent=done?`Selesai ${target} halaman hari ini · ${total} hari konsisten direkodkan.`:`Sasarkan ${target} halaman hari ini. ${total} hari telah direkodkan.`}
function exportData(){try{const payload={app:'NUR Academy',version:C.version,exportedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nur-academy-backup-${localDateKey()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Backup berjaya dieksport.','#backupMessage')}catch(e){toast('Backup tidak dapat dieksport.','#backupMessage')}}
function importData(e){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result);const incoming=parsed.state||parsed;if(!incoming||typeof incoming!=='object')throw 0;const base=defaultState();state=Object.assign(base,incoming);state.preferences=Object.assign(base.preferences,incoming.preferences||{});state.daily=Object.assign(base.daily,incoming.daily||{});state.quranPlan=Object.assign(base.quranPlan,incoming.quranPlan||{});state.ramadan=Object.assign(base.ramadan,incoming.ramadan||{});saveState();applyTheme();setupSettings();renderDhikr();renderHome();renderUpgradeDashboard();updateLocationUI();toast('Backup berjaya dipulihkan.','#backupMessage')}catch(err){toast('Fail backup tidak sah atau rosak.','#backupMessage')}finally{e.target.value=''}};reader.readAsText(file)}
function setupSearch(){$('#globalSearch').oninput=e=>runGlobalSearch(e.target.value);$('#globalSearchSide').oninput=e=>{if(e.target.value.trim()){$('#globalSearch').value=e.target.value;runGlobalSearch(e.target.value)}}}
function runGlobalSearch(q){const term=q.trim().toLowerCase(),results=[];if(!term){$('#globalResults').innerHTML='<div class="empty-state">Taip sesuatu untuk mula mencari.</div>';return}const feature=[['Waktu Solat','Semak lima waktu solat dan countdown.','solat'],['Al-Quran','Cari 114 surah, baca dan dengar audio.','quran'],['Zikir','Kiraan zikir tersimpan pada peranti.','zikir'],['Akademi','Pelajaran asas Islam.','akademi'],['Arah Kiblat','Kira bearing ke Kaabah berdasarkan lokasi.','kiblat'],['Tetapan','Urus tema, nama dan data.','tetapan'],['Ramadan','Rutin Ramadan dan jadual sahur/iftar.','ramadan']];feature.forEach(x=>{if(`${x[0]} ${x[1]}`.toLowerCase().includes(term))results.push({title:x[0],desc:x[1],go:x[2]})});LESSONS.forEach(x=>{if(`${x.title} ${x.intro}`.toLowerCase().includes(term))results.push({title:x.title,desc:x.intro,go:'akademi'})});if(surahs.length)surahs.filter(s=>`${s.number} ${s.englishName} ${s.name} ${s.englishNameTranslation}`.toLowerCase().includes(term)).slice(0,20).forEach(s=>results.push({title:s.englishName,desc:`Surah ${s.number} · ${s.numberOfAyahs} ayat`,surah:s.number}));if(!results.length){$('#globalResults').innerHTML='<div class="empty-state">Tiada hasil ditemui.</div>';return}$('#globalResults').innerHTML=results.slice(0,30).map((r,i)=>`<button class="search-result" data-result="${i}"><strong>${escapeHtml(r.title)}</strong><small>${escapeHtml(r.desc)}</small></button>`).join('');$('#globalResults').onclick=e=>{const b=e.target.closest('[data-result]');if(!b)return;const r=results[Number(b.dataset.result)];if(r.surah)openSurah(r.surah);else showPage(r.go)}}
function renderHome(){const last=state.lastRead;if(last){$('#lastReadHome').textContent=`${last.name||`Surah ${last.surah}`} · Ayat ${last.ayah}`;$('#lastReadHome').parentElement.dataset.readSurah=String(last.surah);$('#lastReadHome').parentElement.dataset.readAyah=String(last.ayah)}else $('#lastReadHome').textContent='Belum ada bacaan terakhir.';const done=Object.values(state.learning).filter(Boolean).length;$('#learningProgress').textContent='Akademi · Coming Soon';const d=DHIKR.find(x=>x.id===state.dhikr.selected)||DHIKR[0],n=Number(state.dhikr[d.id]||0);$('#homeProgress').textContent=`${n} / ${d.target} kiraan ${d.name}.`;const daily=DAILY[Math.floor(Date.now()/86400000)%DAILY.length];$('#dailyTitle').textContent=daily[0];$('#dailyText').textContent=daily[1]}
function setupHome(){document.querySelector('[data-last-read-card]').onclick=e=>{e.preventDefault();const p=e.currentTarget;if(p.dataset.readSurah)openSurah(Number(p.dataset.readSurah),Number(p.dataset.readAyah||0));else showPage('quran')}}
function setupSetupModal(){const modal=$('#setupModal');if(state.setupDone){modal.hidden=true;return}modal.hidden=false;$('#setupName').value=state.profile.name||'';$('#setupTheme').value=state.preferences.theme||'dark';$('#setupNotif').checked=state.preferences.notificationMode!=='off';$('#setupGpsBtn').onclick=()=>useGps('#setupMessage');$('#finishSetupBtn').onclick=async()=>{state.profile.name=$('#setupName').value.trim();state.preferences.theme=$('#setupTheme').value;state.preferences.notificationMode=$('#setupNotif').checked?'0':'off';saveState();if($('#setupCity').value.trim())await geocodeCity($('#setupCity').value.trim());state.setupDone=true;saveState();applyTheme();modal.hidden=true;renderHome();if(state.location)fetchPrayerTimes()}}
function registerPwa(){if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
function setupOnline(){const update=()=>{$('#statusPill').textContent=navigator.onLine?'Dalam talian':'Luar talian'};window.addEventListener('online',update);window.addEventListener('offline',update);update()}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}

function ensureDaily(){const k=localDateKey();if(state.daily.lastDay===k)return;const prev=new Date();prev.setDate(prev.getDate()-1);const old=state.daily.lastDay;state.daily.streak=old===localDateKey(prev)?Number(state.daily.streak||0)+1:1;if(old&&state.daily.prayers&&Object.keys(state.daily.prayers).length)state.daily.history[old]=Object.assign({},state.daily.prayers);state.daily.lastDay=k;state.daily.prayers=state.daily.history[k]?Object.assign({},state.daily.history[k]):{};saveState()}
function markPrayerDone(name){ensureDaily();state.daily.prayers[name]=!state.daily.prayers[name];state.daily.history[localDateKey()]=Object.assign({},state.daily.prayers);saveState();renderPrayerRows(nextPrayer());renderPrayerHistory();renderUpgradeDashboard()}
function renderPrayerHistory(){const box=$('#prayerHistory');if(!box)return;const names=PRAYERS.map(x=>x[1]);const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=localDateKey(d),rec=key===localDateKey()?state.daily.prayers:(state.daily.history[key]||{}),done=names.filter(n=>rec[n]).length;days.push({d,key,done})}const today=days[6];$('#prayerHistoryScore').textContent=`${today.done}/5`;box.innerHTML=days.map(x=>`<div class="history-day ${x.done===5?'done':''}"><strong>${x.d.toLocaleDateString('ms-MY',{weekday:'short'})}</strong><span>${x.done}/5</span></div>`).join('')}
function haptic(){if(state.preferences.haptic&&navigator.vibrate)navigator.vibrate(12)}
function renderUpgradeDashboard(){ensureDaily();const prayers=Object.values(state.daily.prayers||{}).filter(Boolean).length;const dh=DHIKR.find(x=>x.id===state.dhikr.selected)||DHIKR[0],dn=Number(state.dhikr[dh.id]||0);const quranDone=Boolean(state.quranPlan.days?.[localDateKey()]);const pct=Math.round((prayers/5*60)+(Math.min(dn/Number(state.dhikr.target||dh.target),1)*25)+(quranDone?15:0));$('#statPrayer').textContent=`${prayers}/5`;$('#statDhikr').textContent=dn;$('#statLessons').textContent='Soon';$('#statQuran').textContent=state.lastRead?`Ayat ${state.lastRead.ayah}`:'—';$('#streakBadge').textContent=`🔥 ${state.daily.streak||0} hari`;$('#dailyProgressBar').style.width=`${Math.min(100,pct)}%`;const ap=$('#academyProgressText');if(ap)ap.textContent='Coming Soon';const ab=$('#academyProgressBar');if(ab)ab.style.width='0%';const ac=$('#academyCompleted');if(ac)ac.textContent='Coming Soon';const ax=$('#academyXp');if(ax)ax.textContent='—';}
function setupPrayerCompletion(){const box=$('#prayerList');if(!box||box.dataset.upgraded)return;box.dataset.upgraded='1';box.addEventListener('click',e=>{const row=e.target.closest('.prayer-row');if(!row)return;markPrayerDone(row.querySelector('strong')?.textContent||'');row.classList.add('completed');haptic()})}
let compassListening=false,deviceHeading=null;
function qiblaFromHeading(){if(deviceHeading==null||!state.location)return;const q=bearing(Number(state.location.lat),Number(state.location.lon),KAABA.lat,KAABA.lon);let rel=((q-deviceHeading)+360)%360;$('.qibla-arrow').style.transform=`rotate(${rel}deg)`;$('#deviceHeading').textContent=`${deviceHeading.toFixed(1)}°`;$('#qiblaOffset').textContent=`${rel.toFixed(1)}°`;$('#headingReadout').textContent=`${deviceHeading.toFixed(0)}° · Kiblat ${rel.toFixed(0)}°`;$('#qiblaMessage').textContent=`Sensor aktif · Pusingkan peranti sehingga anak panah menunjuk ke arah kiblat.`}
function handleOrientation(e){let h;if(typeof e.webkitCompassHeading==='number')h=e.webkitCompassHeading;else if(typeof e.alpha==='number' && (e.absolute===true || e.type==='deviceorientationabsolute')){const angle=Number(window.screen?.orientation?.angle||0);h=(360-e.alpha+angle)%360}else return;deviceHeading=(h+360)%360;const now=performance.now();if(now-orientationLast<40)return;orientationLast=now;const ring=$('.compass-ring');if(ring)ring.style.transform=`rotate(${-deviceHeading}deg)`;qiblaFromHeading()}
async function startCompass(){if(compassListening)return true;if(!('DeviceOrientationEvent'in window)){toast('Peranti/browser ini tidak menyokong sensor kompas.','#qiblaMessage');return false}try{if(typeof DeviceOrientationEvent.requestPermission==='function'){const permission=await DeviceOrientationEvent.requestPermission();if(permission!=='granted')throw new Error('denied')}window.addEventListener('deviceorientationabsolute',handleOrientation,true);window.addEventListener('deviceorientation',handleOrientation,true);compassListening=true;$('#compassStatus').textContent='Kompas sensor aktif. Pastikan kebenaran sensor diberikan dan jauhkan daripada gangguan magnet.';$('#compassBtn').textContent='Kompas aktif';haptic();return true}catch(e){$('#compassStatus').textContent='Kebenaran sensor tidak diberikan. Bearing geografi masih boleh digunakan.';return false}}
function renderQiblaUpgraded(){renderQibla();if(deviceHeading!=null)qiblaFromHeading()}
function calibrateCompass(){if(!('DeviceOrientationEvent'in window)){toast('Sensor orientasi tidak tersedia.','#compassStatus');return}$('#compassStatus').textContent='Kalibrasi: jauhkan telefon daripada magnet/logam, pegang rata dan gerakkan perlahan dalam bentuk angka 8. Kemudian tekan Kompas aktif.';haptic()}
function setupCompass(){const b=$('#compassBtn');if(b)b.onclick=startCompass;const c=$('#calibrateCompassBtn');if(c)c.onclick=calibrateCompass;const v=$('#qiblaVisual');if(v){let sx=0,sy=0;v.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;v.setPointerCapture?.(e.pointerId)});v.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-sx,e.clientY-sy)>30)startCompass()})}}
function setupQuranUpgrades(){const auto=$('#autoNextToggle'),rep=$('#repeatAyahToggle'),rate=$('#playbackRate');if(auto)auto.checked=state.preferences.autoNext!==false;if(rep)rep.checked=!!state.preferences.repeatAyah;if(rate)rate.value=String(state.preferences.playbackRate||1);const sel=$('#quranTranslation');if(sel){sel.value=state.preferences.quranTranslation||'ms.basmeih';sel.onchange=()=>{state.preferences.quranTranslation=sel.value;saveState();if(currentSurah)openSurah(currentSurahNumber,0)}}const apply=()=>{$$('.arabic').forEach(x=>x.style.fontSize=`${state.preferences.quranFont||31}px`)};$('#quranFontDown').onclick=()=>{state.preferences.quranFont=Math.max(22,(state.preferences.quranFont||31)-2);saveState();apply()};$('#quranFontUp').onclick=()=>{state.preferences.quranFont=Math.min(48,(state.preferences.quranFont||31)+2);saveState();apply()};$('#quranFontReset').onclick=()=>{state.preferences.quranFont=31;saveState();apply()}}
async function fetchQuranCollection(path,label){const msg=$('#quranExploreMessage');if(msg)msg.textContent=`Memuatkan ${label}…`;try{const controller=new AbortController(),t=setTimeout(()=>controller.abort(),7000);const r=await fetch(`${C.quranApi}/${path}` ,{signal:controller.signal,cache:'force-cache'});clearTimeout(t);if(!r.ok)throw 0;const d=await r.json();const a=d?.data?.ayahs?.[0];if(!a)throw 0;const surah=a.surah?.number||a.surah?.numberInSurah;if(surah){await openSurah(Number(surah),Number(a.numberInSurah||1));if(msg)msg.textContent=`Dibuka dari ${label}.`}}catch(e){if(msg)msg.textContent=`${label} tidak dapat dimuatkan sekarang. Cuba lagi.`}}
function setupQuranExplore(){const j=$('#openJuzBtn'),p=$('#openPageBtn');if(j)j.onclick=()=>fetchQuranCollection(`juz/${Number($('#juzSelect').value||1)}`,'juz');if(p)p.onclick=()=>{const n=Math.min(604,Math.max(1,Number($('#pageNumberInput').value||1)));$('#pageNumberInput').value=n;fetchQuranCollection(`page/${n}`,'halaman Quran')}}
function setupSettingsUpgrades(){const h=$('#hapticToggle'),r=$('#reducedDataToggle');if(h){h.checked=!!state.preferences.haptic;h.onchange=()=>{state.preferences.haptic=h.checked;saveState()}}if(r){r.checked=!!state.preferences.reducedData;r.onchange=()=>{state.preferences.reducedData=r.checked;saveState();toast(r.checked?'Mod data rendah diaktifkan.':'Mod data rendah dimatikan.')}}}
function setupUpgrades(){setupPrayerCompletion();setupCompass();setupQuranUpgrades();setupSettingsUpgrades();renderPrayerHistory();renderUpgradeDashboard();const oldAdd=$('#dhikrAddBtn');if(oldAdd&&!oldAdd.dataset.haptic){oldAdd.dataset.haptic='1';oldAdd.addEventListener('click',haptic)}}

function initApp(){try{loadState();applyTheme();setupSideMenu();setupNavigation();setupOnline();setupLocation();setupNotifications();setupAudio();setupQuran();setupNotes();setupDhikr();setupAcademy();setupSettings();setupSearch();setupHome();updateLocationUI();renderHome();clockTimer=setInterval(updateClock,1000);updateClock();notificationTimer=setInterval(checkPrayerNotification,30000);registerPwa();if(state.location&&(!state.location.timings||state.location.dateKey!==localDateKey()))fetchPrayerTimes();const hash=location.hash.replace('#','');if(hash)showPage(hash);setupSetupModal();setupUpgrades()}catch(err){console.error('NUR Academy init error',err);toast('Sebahagian fungsi gagal dimulakan. Cuba muat semula.','#settingsMessage')}finally{window.requestAnimationFrame(()=>window.setTimeout(()=>$('#startupLoader')?.classList.add('hide'),120))}}
document.addEventListener('DOMContentLoaded',initApp);
})();
